### PR TITLE
build fixes for boost 1.58

### PR DESCRIPTION
**Pull request by kljohann**
Can anyone check that this still works for lower boost versions?

### CODE REVIEW

**Comment by thdox** [comment]
I am on Debian stable 8 aka jessie, with libboost-1.55
With this PR #417 ledger does not compile anymore.
Here is the log http://pastebin.com/EmKFEwEj
This has also been reported today by dodekaeder on IRC

**Comment by jwiegley** [comment]
@kljohann I have reverted these two commits, due to the problems encountered by thdox.  We need to test whether these changes can be made to work with older version of Boost first.

**Comment by Ikke** [comment]
This fixes building on Archlinux which already ships boost 1.58. I currently added these commits as patches when I build the packages.

**Comment by jwakely** [comment]
Hi - why was this fix reverted again?

**Comment by jwiegley** [comment]
@jwakely See comment from @thdox above.

**Comment by jwakely** [comment]
Is there a solution that works with both 1.55 and 1.58 though? The current Ledger master doesn't work with the current Boost release.

**Comment by thdox** [comment]
Here is pastebin again, as first one expired.
http://pastebin.com/YHXVvhGe

I would be happy if someone find a fix that enables compilation with both boost 1.55 and 1.58. If you want me to test compilation, please send patch or PR.

**Comment by jwakely** [comment]
This error suggests that making the `xdata_t` type EqualityComparable would work:

    /usr/include/boost/utility/compare_pointees.hpp:32:52: error: no match for ‘operator==’ (operand types are ‘const ledger::post_t::xdata_t’ and ‘const ledger::post_t::xdata_t’)
       return (!x) != (!y) ? false : ( !x ? true : (*x) == (*y) ) ;
                                                        ^

However, since it seems all the problematic lines are simply trying to test if the optional is empty, why not simply do that explicitly instead of comparing to `NULL` or `none`:

    return (bool)x;
