### ISSUE TITLE
`acprep` doesn't work with Python 3.11

### ISSUE THREAD

**Issue by equal-l2** [ledger/ledger#2154]
With python 3.11, `acprep` fails with the following error:
```
acprep: ERROR: Caught exception
Traceback (most recent call last):
  File "/Users/equall2/test/ledger/./acprep", line 196, in run
    argspec = inspect.getargspec(self.main)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
```

**Comment by tbm** [comment]
@afh @q3aiml

**Comment by afh** [comment]
Thanks for bringing this to our attention, @equal-l2. Can you please verify that #2155 fixes this issue?

Thanks for the ping @tbm :pray:

**Comment by tbm** [comment]
I still get:

```
acprep:198: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
```

with

```
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

so it seems that warning was already there at least in Python 3.9.

**Comment by afh** [comment]
@tbm I've put up #2183 for review, seems that [`getfullargspec`](https://docs.python.org/3.9/library/inspect.html#inspect.getfullargspec) has been available since Python 3.0…
