### ISSUE TITLE
Fails to build on macOS (10.14; AppleClang 10.0.0.10001145, boost 1.68)

### ISSUE THREAD

**Issue by tko** [ledger/ledger#1774]
macOS Mojave 10.14.3
The C compiler identification is AppleClang 10.0.0.10001145
The CXX compiler identification is AppleClang 10.0.0.10001145
Boost version: 1.68.0

boost and everything from homebrew, all up to date at the time of writing.

```
In file included from /Users/tko/Projects/ledger/system.hh:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error:
      no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error:
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error:
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^

[and more]

19 errors generated.
make[2]: *** [system.hh.pch] Error 1
make[1]: *** [src/CMakeFiles/libledger.dir/all] Error 2
make: *** [all] Error 2
acprep: ERROR: Execution failed: make
```

<details><p>

```console
% ./acprep make
acprep: INFO: Invoking primary phase: make
acprep: INFO: Executing phase: make
acprep: INFO: Executing phase: config
acprep: INFO: Executing phase: configure
acprep: INFO: System type is => Darwin
acprep: INFO: Setting up build flavor => debug
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Deprecation Warning at CMakeLists.txt:4 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.16")
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   system
--   iostreams
--   regex
--   unit_test_framework
-- Looking for getpwuid
-- Looking for getpwuid - found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for isatty
-- Looking for isatty - found
-- Performing Test UNIX_PIPES_COMPILES
-- Performing Test UNIX_PIPES_COMPILES - Success
-- Performing Test BOOST_REGEX_UNICODE_RUNS
-- Performing Test BOOST_REGEX_UNICODE_RUNS - Failed
-- Looking for readline in edit
-- Looking for readline in edit - found
-- Performing Test HAVE_WORKING_UTFCPP
-- Performing Test HAVE_WORKING_UTFCPP - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tko/Projects/ledger
[  1%] Generating ../system.hh.pch
In file included from /Users/tko/Projects/ledger/system.hh:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error:
      no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error:
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error:
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/math.h:749:12: note:
      'finite' declared here
extern int finite(double)
           ^
In file included from /Users/tko/Projects/ledger/system.hh:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error:
      no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error:
      no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error:
      no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:7: error:
      no member named 'isgreater' in the global namespace; did you mean
      '::std::greater'?
using ::isgreater;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:720:29: note:
      '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /Users/tko/Projects/ledger/system.hh:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:7: error:
      no member named 'isgreaterequal' in the global namespace; did you mean
      '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:749:29: note:
      '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from /Users/tko/Projects/ledger/system.hh:96:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:369:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error:
      no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error:
      no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error:
      no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error:
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error:
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:34:
/usr/local/include/boost/math/special_functions/sign.hpp:30:17: error: no member
      named 'signbit' in namespace 'std'; did you mean simply 'signbit'?
        return (std::signbit)(x) ? 1 : 0;
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:891:8: note:
      'signbit' declared here
   int signbit BOOST_NO_MACRO_EXPAND(T x);
       ^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:35:
/usr/local/include/boost/math/special_functions/fpclassify.hpp:155:12: error:
      no member named 'fpclassify' in namespace 'std'; did you mean simply
      'fpclassify'?
   return (std::fpclassify)(t);
           ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:876:8: note:
      'fpclassify' declared here
   int fpclassify BOOST_NO_MACRO_EXPAND(T t);
       ^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:35:
/usr/local/include/boost/math/special_functions/fpclassify.hpp:314:17: error:
      no member named 'isfinite' in namespace 'std'; did you mean simply
      'isfinite'?
        return (std::isfinite)(x);
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:879:9: note:
      'isfinite' declared here
   bool isfinite BOOST_NO_MACRO_EXPAND(T z);
        ^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:35:
/usr/local/include/boost/math/special_functions/fpclassify.hpp:385:17: error:
      no member named 'isnormal' in namespace 'std'; did you mean simply
      'isnormal'?
        return (std::isnormal)(x);
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:888:9: note:
      'isnormal' declared here
   bool isnormal BOOST_NO_MACRO_EXPAND(T t);
        ^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:35:
/usr/local/include/boost/math/special_functions/fpclassify.hpp:456:17: error:
      no member named 'isinf' in namespace 'std'; did you mean simply 'isinf'?
        return (std::isinf)(x);
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:882:9: note:
      'isinf' declared here
   bool isinf BOOST_NO_MACRO_EXPAND(T t);
        ^
In file included from /Users/tko/Projects/ledger/system.hh:141:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time.hpp:24:
In file included from /usr/local/include/boost/date_time/posix_time/time_formatters.hpp:12:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian.hpp:31:
In file included from /usr/local/include/boost/date_time/gregorian/gregorian_io.hpp:16:
In file included from /usr/local/include/boost/date_time/date_facet.hpp:23:
In file included from /usr/local/include/boost/date_time/period_parser.hpp:14:
In file included from /usr/local/include/boost/date_time/string_parse_tree.hpp:13:
In file included from /usr/local/include/boost/lexical_cast.hpp:32:
In file included from /usr/local/include/boost/lexical_cast/try_lexical_convert.hpp:42:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical.hpp:54:
In file included from /usr/local/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:63:
In file included from /usr/local/include/boost/lexical_cast/detail/inf_nan.hpp:35:
/usr/local/include/boost/math/special_functions/fpclassify.hpp:552:17: error:
      no member named 'isnan' in namespace 'std'; did you mean simply 'isnan'?
        return (std::isnan)(x);
                ^~~~~
/usr/local/include/boost/math/special_functions/math_fwd.hpp:885:9: note:
      'isnan' declared here
   bool isnan BOOST_NO_MACRO_EXPAND(T t);
        ^
19 errors generated.
make[2]: *** [system.hh.pch] Error 1
make[1]: *** [src/CMakeFiles/libledger.dir/all] Error 2
make: *** [all] Error 2
acprep: ERROR: Execution failed: make
```
</p></details>

**Comment by tko** [comment]
Based on googling I tried adding `#include <cmath>` in the beginning of system.hh.in and also changing "math.h" to "cmath" in src/amount.cc but no luck.

**Comment by tko** [comment]
Getting similar errors also with llvm 7 and llvm@6, both from homebrew. gcc8 gets past the headers trouble but fails at linking, possibly due to boost still being built with clang.

**Comment by tko** [comment]
I was able to build ledger with `cmake -DPRECOMPILE_SYSTEM_HH=OFF` and the default AppleClang compiler.

**Comment by kroitor** [comment]
Having the same issue with `./acprep` on MacOS X Mojave 10.14.3... looks like a common thing to many mac packages involving `cmake`.

```
Darwin mbp.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

@tko would be great if you could elaborate a bit more on the procedure (starting with a clean repo), can you write out the exact sequence you used to build it on your Mac? Thx a lot in advance.

**Comment by he-sk** [comment]
@kroitor: Here's what I did to compile based on @tko's suggestion:

````
./acprep gitclean  # probably not necessary
git checkout v3.1.3  # I did a pull before and wanted to have a stable release
# edit line 189 in src/CMakeLists.txt and replace `-isystem` with `-I`
./acprep configure --prefix /usr/local/Cellar/ledger/3.1.3_local2  # I use Homebrew for version management
./acprep opt make
./acprep opt make install
brew switch ledger 3.1.3_local2
````

Below is a patch of my changes

````
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 756df376..003267fa 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -186,7 +186,7 @@ if (CMAKE_BUILD_TYPE STREQUAL "Debug")
 
       get_directory_property(DIRINC INCLUDE_DIRECTORIES)
       foreach(_inc ${DIRINC})
-        list(APPEND _args "-isystem " ${_inc})
+        list(APPEND _args "-I " ${_inc})
       endforeach(_inc ${DIRINC})
 
       separate_arguments(_args)
````

**Comment by kroitor** [comment]
@he-sk thank you for the followup! To be honest, I've managed to resolve this by running `ledger` in a virtualbox linux – the build goes fine there. However, I will try to your solution to see if it works for me. Thx a lot again!

**Comment by tbm** [comment]
Is this still an issue?

**Comment by kroitor** [comment]
@tbm i haven't tested it recently, but if the native mac builds work fine – then this isn't an issue anymore )

**Comment by jwiegley** [comment]
I use Ledger on Mac native.

**Comment by tbm** [comment]
It's not clear to me if this can be closed or not.

@tko can you comment.

**Comment by tko** [comment]
Tried building current master b1d8706fd09e714cb77d7e55d94b4124a90fe662
* `./acprep debug make` fails
* `./acprep opt make` works

**Comment by tbm** [comment]
@tko fails with the error you originally posted?

**Comment by tko** [comment]
@tbm same error
